#stage-1: build
FROM node:20-alpine AS builder
WORKDIR /app

# install deps and build
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# stage-2: runtime - use nginx (doesn't include npm)
FROM nginx:stable-alpine

# clear default content and copy built site
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx","-g","daemon off;"]